version: "3.5"
services:
  myzapdev:
    build: 
      context: .
    image: myzap:${VERSION}
    container_name: myzapdev
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - 3333:3333